export declare const defaultOption: {
    shape: string;
    interval: number;
    decel: number;
    maxSpeed: number;
    minSpeed: number;
    textHeight: number;
    outlineMethod: string;
    fadeIn: number;
    outlineColour: string;
    outlineThickness: number;
    outlineOffset: number;
    depth: number;
    minBrightness: number;
    reverse: boolean;
    shadowBlur: number;
    shuffleTags: boolean;
    shadowOffset: number[];
    stretchX: number;
    initial: number[];
    textFont: null;
    textColour: null;
    weight: boolean;
    weightMode: string;
    weightSize: number;
    weightSizeMax: number;
    weightSizeMin: number;
    weightFrom: string;
    wheelZoom: boolean;
    zoomMax: number;
    zoomMin: number;
    zoomStep: number;
    tooltip: string;
    tooltipClass: string;
    freezeActive: boolean;
};
export declare const defaultColor: string[];
